"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PartyType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PartyTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PartyType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PT_NONE: _PartyType.ValueType  # 0
    PT_PERSON: _PartyType.ValueType  # 1
    PT_ORGANIZATION: _PartyType.ValueType  # 2

class PartyType(_PartyType, metaclass=_PartyTypeEnumTypeWrapper): ...

PT_NONE: PartyType.ValueType  # 0
PT_PERSON: PartyType.ValueType  # 1
PT_ORGANIZATION: PartyType.ValueType  # 2
global___PartyType = PartyType

@typing.final
class BasicID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___BasicID = BasicID

@typing.final
class CreatePartyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PERSON_FIELD_NUMBER: builtins.int
    ORGANIZATION_FIELD_NUMBER: builtins.int
    @property
    def person(self) -> global___Person: ...
    @property
    def organization(self) -> global___Organization: ...
    def __init__(
        self,
        *,
        person: global___Person | None = ...,
        organization: global___Organization | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["organization", b"organization", "party", b"party", "person", b"person"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["organization", b"organization", "party", b"party", "person", b"person"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["party", b"party"]) -> typing.Literal["person", "organization"] | None: ...

global___CreatePartyRequest = CreatePartyRequest

@typing.final
class Person(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    MIDDLE_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    DATE_OF_BIRTH_FIELD_NUMBER: builtins.int
    id: builtins.str
    first_name: builtins.str
    middle_name: builtins.str
    last_name: builtins.str
    @property
    def date_of_birth(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        first_name: builtins.str = ...,
        middle_name: builtins.str = ...,
        last_name: builtins.str = ...,
        date_of_birth: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["date_of_birth", b"date_of_birth"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["date_of_birth", b"date_of_birth", "first_name", b"first_name", "id", b"id", "last_name", b"last_name", "middle_name", b"middle_name"]) -> None: ...

global___Person = Person

@typing.final
class Organization(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    ADMIN_CONTACT_FIELD_NUMBER: builtins.int
    id: builtins.str
    @property
    def admin_contact(self) -> global___Person: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        admin_contact: global___Person | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["admin_contact", b"admin_contact"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["admin_contact", b"admin_contact", "id", b"id"]) -> None: ...

global___Organization = Organization

@typing.final
class Party(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    PERSON_FIELD_NUMBER: builtins.int
    ORGANIZATION_FIELD_NUMBER: builtins.int
    id: builtins.str
    @property
    def person(self) -> global___Person: ...
    @property
    def organization(self) -> global___Organization: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        person: global___Person | None = ...,
        organization: global___Organization | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["organization", b"organization", "party", b"party", "person", b"person"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "organization", b"organization", "party", b"party", "person", b"person"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["party", b"party"]) -> typing.Literal["person", "organization"] | None: ...

global___Party = Party
