# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solidpy_test.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12solidpy_test.proto\x12\x0csolidpy_test\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n\x07\x42\x61sicID\x12\n\n\x02id\x18\x01 \x01(\t\"y\n\x12\x43reatePartyRequest\x12&\n\x06person\x18\x01 \x01(\x0b\x32\x14.solidpy_test.PersonH\x00\x12\x32\n\x0corganization\x18\x02 \x01(\x0b\x32\x1a.solidpy_test.OrganizationH\x00\x42\x07\n\x05party\"\x83\x01\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x31\n\rdate_of_birth\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"G\n\x0cOrganization\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\radmin_contact\x18\x02 \x01(\x0b\x32\x14.solidpy_test.Person\"x\n\x05Party\x12\n\n\x02id\x18\x01 \x01(\t\x12&\n\x06person\x18\x02 \x01(\x0b\x32\x14.solidpy_test.PersonH\x00\x12\x32\n\x0corganization\x18\x03 \x01(\x0b\x32\x1a.solidpy_test.OrganizationH\x00\x42\x07\n\x05party*<\n\tPartyType\x12\x0b\n\x07PT_NONE\x10\x00\x12\r\n\tPT_PERSON\x10\x01\x12\x13\n\x0fPT_ORGANIZATION\x10\x02\x32\xcb\x02\n\x0bSolidPyTest\x12\x38\n\tGetPerson\x12\x15.solidpy_test.BasicID\x1a\x14.solidpy_test.Person\x12\x44\n\x0fGetOrganization\x12\x15.solidpy_test.BasicID\x1a\x1a.solidpy_test.Organization\x12\x36\n\x08GetParty\x12\x15.solidpy_test.BasicID\x1a\x13.solidpy_test.Party\x12\x46\n\x0b\x43reateParty\x12 .solidpy_test.CreatePartyRequest\x1a\x15.solidpy_test.BasicID\x12<\n\x0b\x44\x65leteParty\x12\x15.solidpy_test.BasicID\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solidpy_test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARTYTYPE']._serialized_start=573
  _globals['_PARTYTYPE']._serialized_end=633
  _globals['_BASICID']._serialized_start=98
  _globals['_BASICID']._serialized_end=119
  _globals['_CREATEPARTYREQUEST']._serialized_start=121
  _globals['_CREATEPARTYREQUEST']._serialized_end=242
  _globals['_PERSON']._serialized_start=245
  _globals['_PERSON']._serialized_end=376
  _globals['_ORGANIZATION']._serialized_start=378
  _globals['_ORGANIZATION']._serialized_end=449
  _globals['_PARTY']._serialized_start=451
  _globals['_PARTY']._serialized_end=571
  _globals['_SOLIDPYTEST']._serialized_start=636
  _globals['_SOLIDPYTEST']._serialized_end=967
# @@protoc_insertion_point(module_scope)
